namespace xgpu::windows
{
    //----------------------------------------------------------------------------------

    static constexpr std::array s_OSKeyToKeyboardInputKeyCode
    {
        xgpu::keyboard::digital::KEY_NULL                      // 0
    ,   xgpu::keyboard::digital::KEY_NULL                      // 1
    ,   xgpu::keyboard::digital::KEY_NULL                      // 2
    ,   xgpu::keyboard::digital::KEY_NULL                      // 3
    ,   xgpu::keyboard::digital::KEY_NULL                      // 4
    ,   xgpu::keyboard::digital::KEY_NULL                      // 5
    ,   xgpu::keyboard::digital::KEY_NULL                      // 6
    ,   xgpu::keyboard::digital::KEY_NULL                      // 7
    ,   xgpu::keyboard::digital::KEY_BACKSPACE                 // 8
    ,   xgpu::keyboard::digital::KEY_TAB                       // 9
    ,   xgpu::keyboard::digital::KEY_NULL                      // 10
    ,   xgpu::keyboard::digital::KEY_NULL                      // 11
    ,   xgpu::keyboard::digital::KEY_NULL                      // 12
    ,   xgpu::keyboard::digital::KEY_RETURN                    // 13
    ,   xgpu::keyboard::digital::KEY_NULL                      // 14
    ,   xgpu::keyboard::digital::KEY_NULL                      // 15
    ,   xgpu::keyboard::digital::KEY_LSHIFT                    // 16
    ,   xgpu::keyboard::digital::KEY_LCONTROL                  // 17
    ,   xgpu::keyboard::digital::KEY_NULL                      // 18
    ,   xgpu::keyboard::digital::KEY_NULL                      // 19
    ,   xgpu::keyboard::digital::KEY_NULL                      // 20
    ,   xgpu::keyboard::digital::KEY_NULL                      // 21
    ,   xgpu::keyboard::digital::KEY_NULL                      // 22
    ,   xgpu::keyboard::digital::KEY_NULL                      // 23
    ,   xgpu::keyboard::digital::KEY_NULL                      // 24
    ,   xgpu::keyboard::digital::KEY_NULL                      // 25
    ,   xgpu::keyboard::digital::KEY_NULL                      // 26
    ,   xgpu::keyboard::digital::KEY_ESCAPE                    // 27
    ,   xgpu::keyboard::digital::KEY_NULL                      // 28
    ,   xgpu::keyboard::digital::KEY_NULL                      // 29
    ,   xgpu::keyboard::digital::KEY_NULL                      // 30
    ,   xgpu::keyboard::digital::KEY_NULL                      // 31
    ,   xgpu::keyboard::digital::KEY_SPACE                     // 32
    ,   xgpu::keyboard::digital::KEY_PAGEUP                    // 33
    ,   xgpu::keyboard::digital::KEY_PAGEDOWN                  // 34
    ,   xgpu::keyboard::digital::KEY_END                       // 35
    ,   xgpu::keyboard::digital::KEY_HOME                      // 36
    ,   xgpu::keyboard::digital::KEY_LEFT                      // 37
    ,   xgpu::keyboard::digital::KEY_UP                        // 38
    ,   xgpu::keyboard::digital::KEY_RIGHT                     // 39
    ,   xgpu::keyboard::digital::KEY_DOWN                      // 40
    ,   xgpu::keyboard::digital::KEY_NULL                      // 41
    ,   xgpu::keyboard::digital::KEY_NULL                      // 42
    ,   xgpu::keyboard::digital::KEY_PLUS                      // 43
    ,   xgpu::keyboard::digital::KEY_COMMA                     // 44
    ,   xgpu::keyboard::digital::KEY_INSERT                    // 45
    ,   xgpu::keyboard::digital::KEY_DELETE                    // 46
    ,   xgpu::keyboard::digital::KEY_SLASH                     // 47
    ,   xgpu::keyboard::digital::KEY_0                         // 48
    ,   xgpu::keyboard::digital::KEY_1                         // 49
    ,   xgpu::keyboard::digital::KEY_2                         // 50
    ,   xgpu::keyboard::digital::KEY_3                         // 51
    ,   xgpu::keyboard::digital::KEY_4                         // 52
    ,   xgpu::keyboard::digital::KEY_5                         // 53
    ,   xgpu::keyboard::digital::KEY_6                         // 54
    ,   xgpu::keyboard::digital::KEY_7                         // 55
    ,   xgpu::keyboard::digital::KEY_8                         // 56
    ,   xgpu::keyboard::digital::KEY_9                         // 57
    ,   xgpu::keyboard::digital::KEY_SEMICOLON                 // 58
    ,   xgpu::keyboard::digital::KEY_NULL                      // 59
    ,   xgpu::keyboard::digital::KEY_NULL                      // 60
    ,   xgpu::keyboard::digital::KEY_NULL                      // 61
    ,   xgpu::keyboard::digital::KEY_NULL                      // 62
    ,   xgpu::keyboard::digital::KEY_NULL                      // 63
    ,   xgpu::keyboard::digital::KEY_NULL                      // 64
    ,   xgpu::keyboard::digital::KEY_A                         // 65
    ,   xgpu::keyboard::digital::KEY_B                         // 66
    ,   xgpu::keyboard::digital::KEY_C                         // 67
    ,   xgpu::keyboard::digital::KEY_D                         // 68
    ,   xgpu::keyboard::digital::KEY_E                         // 69
    ,   xgpu::keyboard::digital::KEY_F                         // 70
    ,   xgpu::keyboard::digital::KEY_G                         // 71
    ,   xgpu::keyboard::digital::KEY_H                         // 72
    ,   xgpu::keyboard::digital::KEY_I                         // 73
    ,   xgpu::keyboard::digital::KEY_J                         // 74
    ,   xgpu::keyboard::digital::KEY_K                         // 75
    ,   xgpu::keyboard::digital::KEY_L                         // 76
    ,   xgpu::keyboard::digital::KEY_M                         // 77
    ,   xgpu::keyboard::digital::KEY_N                         // 78
    ,   xgpu::keyboard::digital::KEY_O                         // 79
    ,   xgpu::keyboard::digital::KEY_P                         // 80
    ,   xgpu::keyboard::digital::KEY_Q                         // 81
    ,   xgpu::keyboard::digital::KEY_R                         // 82
    ,   xgpu::keyboard::digital::KEY_S                         // 83
    ,   xgpu::keyboard::digital::KEY_T                         // 84
    ,   xgpu::keyboard::digital::KEY_U                         // 85
    ,   xgpu::keyboard::digital::KEY_V                         // 86
    ,   xgpu::keyboard::digital::KEY_W                         // 87
    ,   xgpu::keyboard::digital::KEY_X                         // 88
    ,   xgpu::keyboard::digital::KEY_Y                         // 89
    ,   xgpu::keyboard::digital::KEY_Z                         // 90
    ,   xgpu::keyboard::digital::KEY_LBRACKET                  // 91
    ,   xgpu::keyboard::digital::KEY_BACKSLASH                 // 92
    ,   xgpu::keyboard::digital::KEY_RBRACKET                  // 93
    ,   xgpu::keyboard::digital::KEY_NULL                      // 94
    ,   xgpu::keyboard::digital::KEY_NULL                      // 95
    ,   xgpu::keyboard::digital::KEY_0                         // 96
    ,   xgpu::keyboard::digital::KEY_1                         // 97
    ,   xgpu::keyboard::digital::KEY_2                         // 98
    ,   xgpu::keyboard::digital::KEY_3                         // 99
    ,   xgpu::keyboard::digital::KEY_4                         // 100
    ,   xgpu::keyboard::digital::KEY_5                         // 101
    ,   xgpu::keyboard::digital::KEY_6                         // 102
    ,   xgpu::keyboard::digital::KEY_7                         // 103
    ,   xgpu::keyboard::digital::KEY_8                         // 104
    ,   xgpu::keyboard::digital::KEY_9                         // 105
    ,   xgpu::keyboard::digital::KEY_MULTIPLY                  // 106
    ,   xgpu::keyboard::digital::KEY_PLUS                      // 107
    ,   xgpu::keyboard::digital::KEY_NULL                      // 108
    ,   xgpu::keyboard::digital::KEY_MINUS                     // 109
    ,   xgpu::keyboard::digital::KEY_PERIOD                    // 110
    ,   xgpu::keyboard::digital::KEY_SLASH                     // 111
    ,   xgpu::keyboard::digital::KEY_P                         // 112
    ,   xgpu::keyboard::digital::KEY_Q                         // 113
    ,   xgpu::keyboard::digital::KEY_R                         // 114
    ,   xgpu::keyboard::digital::KEY_S                         // 115
    ,   xgpu::keyboard::digital::KEY_T                         // 116
    ,   xgpu::keyboard::digital::KEY_U                         // 117
    ,   xgpu::keyboard::digital::KEY_V                         // 118
    ,   xgpu::keyboard::digital::KEY_W                         // 119
    ,   xgpu::keyboard::digital::KEY_X                         // 120
    ,   xgpu::keyboard::digital::KEY_Y                         // 121
    ,   xgpu::keyboard::digital::KEY_Z                         // 122
    ,   xgpu::keyboard::digital::KEY_LBRACKET                  // 123
    ,   xgpu::keyboard::digital::KEY_NULL                      // 124
    ,   xgpu::keyboard::digital::KEY_RBRACKET                  // 125
    ,   xgpu::keyboard::digital::KEY_TILDE                     // 126
    ,   xgpu::keyboard::digital::KEY_BACKSPACE                 // 127
    ,   xgpu::keyboard::digital::KEY_NULL                      // 128
    ,   xgpu::keyboard::digital::KEY_NULL                      // 129
    ,   xgpu::keyboard::digital::KEY_NULL                      // 130
    ,   xgpu::keyboard::digital::KEY_NULL                      // 131
    ,   xgpu::keyboard::digital::KEY_NULL                      // 132
    ,   xgpu::keyboard::digital::KEY_NULL                      // 133
    ,   xgpu::keyboard::digital::KEY_NULL                      // 134
    ,   xgpu::keyboard::digital::KEY_NULL                      // 135
    ,   xgpu::keyboard::digital::KEY_NULL                      // 136
    ,   xgpu::keyboard::digital::KEY_NULL                      // 137
    ,   xgpu::keyboard::digital::KEY_NULL                      // 138
    ,   xgpu::keyboard::digital::KEY_NULL                      // 139
    ,   xgpu::keyboard::digital::KEY_NULL                      // 140
    ,   xgpu::keyboard::digital::KEY_NULL                      // 141
    ,   xgpu::keyboard::digital::KEY_NULL                      // 142
    ,   xgpu::keyboard::digital::KEY_NULL                      // 143
    ,   xgpu::keyboard::digital::KEY_NULL                      // 144
    ,   xgpu::keyboard::digital::KEY_NULL                      // 145
    ,   xgpu::keyboard::digital::KEY_NULL                      // 146
    ,   xgpu::keyboard::digital::KEY_NULL                      // 147
    ,   xgpu::keyboard::digital::KEY_NULL                      // 148
    ,   xgpu::keyboard::digital::KEY_NULL                      // 149
    ,   xgpu::keyboard::digital::KEY_NULL                      // 150
    ,   xgpu::keyboard::digital::KEY_NULL                      // 151
    ,   xgpu::keyboard::digital::KEY_NULL                      // 152
    ,   xgpu::keyboard::digital::KEY_NULL                      // 153
    ,   xgpu::keyboard::digital::KEY_NULL                      // 154
    ,   xgpu::keyboard::digital::KEY_NULL                      // 155
    ,   xgpu::keyboard::digital::KEY_NULL                      // 156
    ,   xgpu::keyboard::digital::KEY_NULL                      // 157
    ,   xgpu::keyboard::digital::KEY_NULL                      // 158
    ,   xgpu::keyboard::digital::KEY_NULL                      // 159
    ,   xgpu::keyboard::digital::KEY_NULL                      // 160
    ,   xgpu::keyboard::digital::KEY_NULL                      // 161
    ,   xgpu::keyboard::digital::KEY_NULL                      // 162
    ,   xgpu::keyboard::digital::KEY_NULL                      // 163
    ,   xgpu::keyboard::digital::KEY_NULL                      // 164
    ,   xgpu::keyboard::digital::KEY_NULL                      // 165
    ,   xgpu::keyboard::digital::KEY_NULL                      // 166
    ,   xgpu::keyboard::digital::KEY_NULL                      // 167
    ,   xgpu::keyboard::digital::KEY_NULL                      // 168
    ,   xgpu::keyboard::digital::KEY_NULL                      // 169
    ,   xgpu::keyboard::digital::KEY_NULL                      // 170
    ,   xgpu::keyboard::digital::KEY_NULL                      // 171
    ,   xgpu::keyboard::digital::KEY_NULL                      // 172
    ,   xgpu::keyboard::digital::KEY_NULL                      // 173
    ,   xgpu::keyboard::digital::KEY_NULL                      // 174
    ,   xgpu::keyboard::digital::KEY_NULL                      // 175
    ,   xgpu::keyboard::digital::KEY_NULL                      // 176
    ,   xgpu::keyboard::digital::KEY_NULL                      // 177
    ,   xgpu::keyboard::digital::KEY_NULL                      // 178
    ,   xgpu::keyboard::digital::KEY_NULL                      // 179
    ,   xgpu::keyboard::digital::KEY_NULL                      // 180
    ,   xgpu::keyboard::digital::KEY_NULL                      // 181
    ,   xgpu::keyboard::digital::KEY_NULL                      // 182
    ,   xgpu::keyboard::digital::KEY_NULL                      // 183
    ,   xgpu::keyboard::digital::KEY_NULL                      // 184
    ,   xgpu::keyboard::digital::KEY_NULL                      // 185
    ,   xgpu::keyboard::digital::KEY_NULL                      // 186
    ,   xgpu::keyboard::digital::KEY_NULL                      // 187
    ,   xgpu::keyboard::digital::KEY_NULL                      // 188
    ,   xgpu::keyboard::digital::KEY_COMMA                     // 189
    ,   xgpu::keyboard::digital::KEY_PERIOD                    // 190
    ,   xgpu::keyboard::digital::KEY_SLASH                     // 191
    ,   xgpu::keyboard::digital::KEY_TILDE                     // 192
    ,   xgpu::keyboard::digital::KEY_NULL                      // 193
    ,   xgpu::keyboard::digital::KEY_NULL                      // 194
    ,   xgpu::keyboard::digital::KEY_NULL                      // 195
    ,   xgpu::keyboard::digital::KEY_NULL                      // 196
    ,   xgpu::keyboard::digital::KEY_NULL                      // 197
    ,   xgpu::keyboard::digital::KEY_NULL                      // 198
    ,   xgpu::keyboard::digital::KEY_NULL                      // 199
    ,   xgpu::keyboard::digital::KEY_NULL                      // 200
    ,   xgpu::keyboard::digital::KEY_NULL                      // 201
    ,   xgpu::keyboard::digital::KEY_NULL                      // 202
    ,   xgpu::keyboard::digital::KEY_NULL                      // 203
    ,   xgpu::keyboard::digital::KEY_NULL                      // 204
    ,   xgpu::keyboard::digital::KEY_NULL                      // 205
    ,   xgpu::keyboard::digital::KEY_NULL                      // 206
    ,   xgpu::keyboard::digital::KEY_NULL                      // 207
    ,   xgpu::keyboard::digital::KEY_NULL                      // 208
    ,   xgpu::keyboard::digital::KEY_NULL                      // 209
    ,   xgpu::keyboard::digital::KEY_NULL                      // 210
    ,   xgpu::keyboard::digital::KEY_NULL                      // 211
    ,   xgpu::keyboard::digital::KEY_NULL                      // 212
    ,   xgpu::keyboard::digital::KEY_NULL                      // 213
    ,   xgpu::keyboard::digital::KEY_NULL                      // 214
    ,   xgpu::keyboard::digital::KEY_NULL                      // 215
    ,   xgpu::keyboard::digital::KEY_NULL                      // 216
    ,   xgpu::keyboard::digital::KEY_NULL                      // 217
    ,   xgpu::keyboard::digital::KEY_NULL                      // 218
    ,   xgpu::keyboard::digital::KEY_NULL                      // 219
    ,   xgpu::keyboard::digital::KEY_NULL                      // 220
    ,   xgpu::keyboard::digital::KEY_NULL                      // 221
    ,   xgpu::keyboard::digital::KEY_NULL                      // 222
    ,   xgpu::keyboard::digital::KEY_NULL                      // 223
    ,   xgpu::keyboard::digital::KEY_NULL                      // 224
    ,   xgpu::keyboard::digital::KEY_NULL                      // 225
    ,   xgpu::keyboard::digital::KEY_NULL                      // 226
    ,   xgpu::keyboard::digital::KEY_NULL                      // 227
    ,   xgpu::keyboard::digital::KEY_NULL                      // 228
    ,   xgpu::keyboard::digital::KEY_NULL                      // 229
    ,   xgpu::keyboard::digital::KEY_NULL                      // 230
    ,   xgpu::keyboard::digital::KEY_NULL                      // 231
    ,   xgpu::keyboard::digital::KEY_NULL                      // 232
    ,   xgpu::keyboard::digital::KEY_NULL                      // 233
    ,   xgpu::keyboard::digital::KEY_NULL                      // 234
    ,   xgpu::keyboard::digital::KEY_NULL                      // 235
    ,   xgpu::keyboard::digital::KEY_NULL                      // 236
    ,   xgpu::keyboard::digital::KEY_NULL                      // 237
    ,   xgpu::keyboard::digital::KEY_NULL                      // 238
    ,   xgpu::keyboard::digital::KEY_NULL                      // 239
    ,   xgpu::keyboard::digital::KEY_NULL                      // 240
    ,   xgpu::keyboard::digital::KEY_NULL                      // 241
    ,   xgpu::keyboard::digital::KEY_NULL                      // 242
    ,   xgpu::keyboard::digital::KEY_NULL                      // 243
    ,   xgpu::keyboard::digital::KEY_NULL                      // 244
    ,   xgpu::keyboard::digital::KEY_NULL                      // 245
    ,   xgpu::keyboard::digital::KEY_NULL                      // 246
    ,   xgpu::keyboard::digital::KEY_NULL                      // 247
    ,   xgpu::keyboard::digital::KEY_NULL                      // 248
    ,   xgpu::keyboard::digital::KEY_NULL                      // 249
    ,   xgpu::keyboard::digital::KEY_NULL                      // 250
    ,   xgpu::keyboard::digital::KEY_NULL                      // 251
    ,   xgpu::keyboard::digital::KEY_NULL                      // 252
    ,   xgpu::keyboard::digital::KEY_NULL                      // 253
    ,   xgpu::keyboard::digital::KEY_NULL                      // 254
    ,   xgpu::keyboard::digital::KEY_NULL                      // 255
    };

    //----------------------------------------------------------------------------------
    constexpr XGPU_INLINE
    int OSKeyToKeyboardInputKeyCode( const int Key ) noexcept
    {
        return (int)s_OSKeyToKeyboardInputKeyCode[Key];
    }
}