// Auto-generated by NodeBuilder 'AddTwoGen' - do not hand-edit; re-run NodeBuilder instead
#include "../../SDK/xnode_os_plugin_api.h"
#include "../../SDK/xnode_os_shared_types.h"
#include "dependencies/xresource_guid/source/xresource_guid.h"
#include <cmath>
#include <algorithm>
#include <cstdlib>

namespace
{
    struct AddTwoGen_node : xnode_os_node
    {
        // Stable per-instance guids for the pins below - reflected (DONT_SHOW) so the saved value is
        // restored on load rather than a fresh xresource::guid_generator::Instance64() regenerating
        // (which would stop matching any saved link) - same pattern end_marker_node.cpp's m_OwnerGuid
        // uses.
        std::uint64_t m_AGuid   = xresource::guid_generator::Instance64();
        std::uint64_t m_BGuid   = xresource::guid_generator::Instance64();
        std::uint64_t m_SumGuid = xresource::guid_generator::Instance64();

        XPROPERTY_VDEF
        ( "AddTwoGen_node", AddTwoGen_node
        , obj_member<"AGuid",   &AddTwoGen_node::m_AGuid,   member_flags<xproperty::flags::DONT_SHOW>>
        , obj_member<"BGuid",   &AddTwoGen_node::m_BGuid,   member_flags<xproperty::flags::DONT_SHOW>>
        , obj_member<"SumGuid", &AddTwoGen_node::m_SumGuid, member_flags<xproperty::flags::DONT_SHOW>>
        )

        // Per-instance port guids (not a shared static array) - every pin needs its own stable identity
        // unique to THIS node instance so links can reference it by guid rather than by array position
        // (see xnode_os_port_desc::m_Guid's own comment; link_instance no longer stores a plain index).
        // Not const-only-initialized - getInputs()/getOutputs() re-sync m_Guid from the reflected
        // fields above on every call, so a guid restored by deserialization AFTER construction still
        // takes effect.
        mutable xnode_os_port_desc m_Inputs[2]  = { { "A", "Float", true, true, false, 0 }
                                                   , { "B", "Float", true, true, false, 0 }
                                                   };
        mutable xnode_os_port_desc m_Outputs[1] = { { "Sum", "Float", true, true, false, 0 } };

        std::span<const xnode_os_port_desc> getInputs() const noexcept override
        {
            m_Inputs[0].m_Guid = m_AGuid;
            m_Inputs[1].m_Guid = m_BGuid;
            return m_Inputs;
        }
        std::span<const xnode_os_port_desc> getOutputs() const noexcept override
        {
            m_Outputs[0].m_Guid = m_SumGuid;
            return m_Outputs;
        }
        void Execute(void** Inputs, void** Outputs) noexcept override
        {
    const float v1_1 = *static_cast<const float*>(Inputs[0]);
    const float v1_2 = *static_cast<const float*>(Inputs[1]);
    const float v2_0 = (v1_1 + v1_2);
    { auto* p = static_cast<float*>(std::malloc(sizeof(float))); *p = v2_0; Outputs[0] = p; }
        }
        void FreeOutputs(void** Outputs) noexcept override
        {
            std::free(Outputs[0]);
        }
    };
}
XPROPERTY_VREG(AddTwoGen_node)

namespace
{
    struct AddTwoGen_node_factory : xnode_os_node_factory
    {
        XPROPERTY_VDEF("AddTwoGen_node_factory", AddTwoGen_node_factory)
        std::string_view getVersion()  const noexcept override { return "1.0"; }
        std::string_view getName()     const noexcept override { return "AddTwoGen"; }
        std::string_view getCategory() const noexcept override { return "Generated"; }
        xnode_os_node& CreateNodeInstance() override { auto* p = new AddTwoGen_node(); p->m_pFactory = this; return *p; }
        void DestroyNodeInstance(xnode_os_node& N) override { delete static_cast<AddTwoGen_node*>(&N); }
    };
}
XPROPERTY_VREG(AddTwoGen_node_factory)

extern "C" XNODE_OS_EXPORT xnode_os_node_factory& NodeOS_CreateFactory(ixnode_os_host&) noexcept { return *new AddTwoGen_node_factory(); }
extern "C" XNODE_OS_EXPORT void NodeOS_DestroyFactory(xnode_os_node_factory& F) noexcept { delete static_cast<AddTwoGen_node_factory*>(&F); }
