// Auto-generated by NodeBuilder 'AddTwoGen' - do not hand-edit; re-run NodeBuilder instead
#include "../../SDK/xnode_os_plugin_api.h"
#include "../../SDK/xnode_os_shared_types.h"
#include <cmath>
#include <algorithm>
#include <cstdlib>

namespace
{
    struct AddTwoGen_node : xnode_os_node
    {
        XPROPERTY_VDEF("AddTwoGen_node", AddTwoGen_node)

        std::span<const xnode_os_port_desc> getInputs() const noexcept override
        { static const xnode_os_port_desc s_Inputs[] = { { "A", "Float" }, { "B", "Float" },  }; return s_Inputs; }
        std::span<const xnode_os_port_desc> getOutputs() const noexcept override
        { static const xnode_os_port_desc s_Outputs[] = { { "Sum", "Float" },  }; return s_Outputs; }
        void Execute(void** Inputs, void** Outputs) noexcept override
        {
    const float v1_1 = *static_cast<const float*>(Inputs[0]);
    const float v1_2 = *static_cast<const float*>(Inputs[1]);
    const float v2_0 = (v1_1 + v1_2);
    { auto* p = static_cast<float*>(std::malloc(sizeof(float))); *p = v2_0; Outputs[0] = p; }
        }
        void FreeOutputs(void** Outputs) noexcept override
        {
            std::free(Outputs[0]);
        }
    };
}
XPROPERTY_VREG(AddTwoGen_node)

namespace
{
    struct AddTwoGen_node_factory : xnode_os_node_factory
    {
        XPROPERTY_VDEF("AddTwoGen_node_factory", AddTwoGen_node_factory)
        std::string_view getVersion()  const noexcept override { return "1.0"; }
        std::string_view getName()     const noexcept override { return "AddTwoGen"; }
        std::string_view getCategory() const noexcept override { return "Generated"; }
        xnode_os_node& CreateNodeInstance() override { auto* p = new AddTwoGen_node(); p->m_pFactory = this; return *p; }
        void DestroyNodeInstance(xnode_os_node& N) override { delete static_cast<AddTwoGen_node*>(&N); }
    };
}
XPROPERTY_VREG(AddTwoGen_node_factory)

extern "C" XNODE_OS_EXPORT xnode_os_node_factory& NodeOS_CreateFactory(ixnode_os_host&) noexcept { return *new AddTwoGen_node_factory(); }
extern "C" XNODE_OS_EXPORT void NodeOS_DestroyFactory(xnode_os_node_factory& F) noexcept { delete static_cast<AddTwoGen_node_factory*>(&F); }
